<?php

/**
 * @file
 * Contains m2group.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function m2group_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the m2group module.
    case 'help.page.m2group':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('m2group module') . '</p>';
      return $output;

    default:
  }
}
